In [4]:
import sys

print(sys.version)
print(sys.executable)

3.13.16 (tags/v3.13.16:cbc944f, Sep 30 2026, 19:17:50) [MSC v.1944 64 bit (AMD64)]
d:\Product Management\Koushik-Projects\AI-ML-Experiments\.venv\Scripts\python.exe

In [5]:
import pandas as pd
from pathlib import Path

data_path = Path("../data/quikr_car.csv")

df = pd.read_csv(data_path)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

display(df.head())

Dataset loaded successfully!
Dataset shape: (892, 6)

Column names:
['name', 'company', 'year', 'Price', 'kms_driven', 'fuel_type']

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [6]:
# 1. Inspect data types and non-null counts
print("DATASET INFORMATION")
df.info()

# 2. Check missing values
print("\nMISSING VALUES")
print(df.isnull().sum())

# 3. Inspect a few records
print("\nSAMPLE RECORDS")
display(df.head(10))

# 4. Check duplicate rows
print("\nDUPLICATE ROWS")
print(df.duplicated().sum())

DATASET INFORMATION
<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str
 1   company     892 non-null    str
 2   year        892 non-null    str
 3   Price       892 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: str(6)
memory usage: 92.3 KB

MISSING VALUES
name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

SAMPLE RECORDS

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
5,Ford EcoSport Titanium 1.5L TDCi,Ford,2015,Ask For Price,"59,000 kms",Diesel
6,Ford Figo,Ford,2012,"1,75,000","41,000 kms",Diesel
7,Hyundai Eon,Hyundai,2013,"1,90,000","25,000 kms",Petrol
8,Ford EcoSport Ambiente 1.5L TDCi,Ford,2016,"8,30,000","24,530 kms",Diesel
9,Maruti Suzuki Alto K10 VXi AMT,Maruti,2015,"2,50,000","60,000 kms",Petrol

DUPLICATE ROWS
94

In [7]:

# Examine different values and formatting in each column

for column in df.columns:
    print(f"\n--- {column} ---")
    print("Unique values:", df[column].nunique(dropna=False))
    print(df[column].value_counts(dropna=False).head(10))

--- name ---
Unique values: 525
name
Honda City                                 13
Honda Amaze                                11
Maruti Suzuki Dzire                        10
Mahindra Scorpio S10                        9
Maruti Suzuki Alto 800 Lxi                  9
Maruti Suzuki Swift Dzire VXi 1.2 BS IV     7
Mahindra Jeep CL550 MDI                     6
Mini Cooper S 1.6                           6
Renault Duster                              6
Mahindra Quanto C8                          6
Name: count, dtype: int64

--- company ---
Unique values: 48
company
Maruti        235
Hyundai       145
Mahindra      100
Tata           74
Honda          61
Toyota         39
Chevrolet      35
Renault        34
Ford           31
Volkswagen     20
Name: count, dtype: int64

--- year ---
Unique values: 61
year
2015    117
2014     94
2013     94
2016     76
2012     75
2011     60
2017     56
2009     56
2010     44
2018     34
Name: count, dtype: int64

--- Price ---
Unique values: 274
Price
Ask For Price    35
2,50,000         17
3,50,000         14
1,80,000         13
4,00,000         12
1,30,000         12
2,20,000         11
4,50,000         11
1,50,000         11
3,00,000         11
Name: count, dtype: int64

--- kms_driven ---
Unique values: 259
kms_driven
NaN           52
45,000 kms    30
35,000 kms    30
55,000 kms    25
50,000 kms    23
20,000 kms    22
60,000 kms    20
30,000 kms    19
40,000 kms    18
41,000 kms    16
Name: count, dtype: int64

--- fuel_type ---
Unique values: 4
fuel_type
Petrol    440
Diesel    395
NaN        55
LPG         2
Name: count, dtype: int64

In [8]:

print("PRICE VALUES THAT ARE NOT SIMPLE NUMBERS")
print(df.loc[~df["Price"].str.replace(",", "", regex=False).str.isnumeric(), "Price"]
      .value_counts()
      .head(20))

print("\nYEAR VALUES")
print(df["year"].value_counts(dropna=False).head(20))

print("\nSAMPLE MILEAGE VALUES")
print(df["kms_driven"].dropna().sample(
    n=min(10, df["kms_driven"].notna().sum()),
    random_state=42
).tolist())

PRICE VALUES THAT ARE NOT SIMPLE NUMBERS
Price
Ask For Price    35
Name: count, dtype: int64

YEAR VALUES
year
2015    117
2014     94
2013     94
2016     76
2012     75
2011     60
2017     56
2009     56
2010     44
2018     34
2006     22
2019     22
2007     19
2008     16
2005     13
2003     13
2004     12
2000      7
2002      5
2001      5
Name: count, dtype: int64

SAMPLE MILEAGE VALUES
['00 kms', '1,20,000 kms', '35,522 kms', '1,60,000 kms', '35,000 kms', '13,000 kms', '37,518 kms', '1,800 kms', '99,000 kms', '73,000 kms']

In [9]:

import pandas as pd

# Preserve the original dataset
df_raw = df.copy()

# Create a separate working copy
df_clean = df_raw.copy()

# 1. Clean the price column
df_clean["Price"] = (
    df_clean["Price"]
    .str.replace(",", "", regex=False)
    .str.strip()
)

df_clean["Price"] = pd.to_numeric(
    df_clean["Price"], errors="coerce"
)

# 2. Clean the manufacturing year
df_clean["year"] = pd.to_numeric(
    df_clean["year"].str.strip(),
    errors="coerce"
)

# 3. Clean the mileage column
df_clean["kms_driven"] = (
    df_clean["kms_driven"]
    .str.replace(",", "", regex=False)
    .str.replace(r"\s*kms\s*$", "", regex=True)
    .str.strip()
)

df_clean["kms_driven"] = pd.to_numeric(
    df_clean["kms_driven"], errors="coerce"
)

# 4. Standardize text formatting
for column in ["name", "company", "fuel_type"]:
    df_clean[column] = df_clean[column].str.strip()

print("Original dataset shape:", df_raw.shape)
print("Working dataset shape:", df_clean.shape)

print("\nData types after cleaning:")
print(df_clean.dtypes)

print("\nMissing values after conversion:")
print(df_clean.isna().sum())

display(df_clean.head())

Original dataset shape: (892, 6)
Working dataset shape: (892, 6)

Data types after cleaning:
name              str
company           str
year          float64
Price         float64
kms_driven    float64
fuel_type         str
dtype: object

Missing values after conversion:
name           0
company        0
year          50
Price         35
kms_driven    54
fuel_type     55
dtype: int64

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007.0,80000.0,45000.0,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006.0,425000.0,40.0,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018.0,NaN,22000.0,Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014.0,325000.0,28000.0,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014.0,575000.0,36000.0,Diesel

In [10]:

# Find the original year values that could not be converted
invalid_years = df_raw.loc[
    pd.to_numeric(df_raw["year"].str.strip(), errors="coerce").isna(),
    "year"
]

print("Invalid or missing year entries:")
print(invalid_years.value_counts(dropna=False))

# Find the original mileage values that became missing
invalid_mileage = df_raw.loc[
    df_clean["kms_driven"].isna() & df_raw["kms_driven"].notna(),
    "kms_driven"
]

print("\nMileage entries that failed conversion:")
print(invalid_mileage.value_counts(dropna=False))

# Check numeric ranges
print("\nNumeric column summary:")
display(df_clean[["year", "Price", "kms_driven"]].describe())

Invalid or missing year entries:
year
...     3
Zest    3
sale    3
o...    3
car     2
d...    2
150k    1
TOUR    1
r 15    1
/-Rs    1
ara)    1
SELL    1
tion    1
odel    1
2 bs    1
arry    1
Eon     1
ture    1
emi     1
able    1
no.     1
SALE    1
digo    1
sell    1
d Ex    1
n...    1
e...    1
D...    1
, Ac    1
go .    1
k...    1
o c4    1
zire    1
cent    1
Sumo    1
cab     1
t xe    1
EV2     1
r...    1
zest    1
Name: count, dtype: int64

Mileage entries that failed conversion:
kms_driven
Petrol    2
Name: count, dtype: int64

Numeric column summary:

              year         Price     kms_driven
count   842.000000  8.570000e+02     838.000000
mean   2012.523753  4.046885e+05   46010.550119
std       4.024601  4.655365e+05   34469.626299
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   25000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.850000e+05   56437.500000
max    2019.000000  8.500003e+06  400000.000000

In [11]:

# Show all rows where the year is not numeric
year_is_invalid = pd.to_numeric(
    df_raw["year"].str.strip(),
    errors="coerce"
).isna()

print("Rows with invalid years:")
display(df_raw.loc[year_is_invalid].head(15))

# Show rows where mileage contains unexpected text
mileage_is_suspicious = (
    df_raw["kms_driven"].str.contains(
        "Petrol", case=False, na=False
    )
)

print("\nRows where mileage contains 'Petrol':")
display(df_raw.loc[mileage_is_suspicious])

# Show numeric ranges after conversion
print("\nNumeric summary:")
display(
    df_clean[["year", "Price", "kms_driven"]].describe()
)

Rows with invalid years:

,name,company,year,Price,kms_driven,fuel_type
185,"Commercial , DZire LDI, 2016, for sale",Commercial,...,Ask For Price,NaN,NaN
195,"Tata indigo ecs LX, 201",Tata,150k,"1,50,000",NaN,NaN
206,MARUTI SUZUKI DESI,MARUTI,TOUR,"4,00,000",NaN,NaN
286,"Commercial , DZire LDI, 2016, for sale",Commercial,...,Ask For Price,NaN,NaN
294,Yama,Yamaha,r 15,"55,000",NaN,NaN
360,selling car Ta,selling,Zest,Ask For Price,NaN,NaN
368,Tata Zest 90,Tata,/-Rs,Ask For Price,NaN,NaN
385,Maruti Suzuki Swift Dzire car,Maruti,sale,"3,00,000",NaN,NaN
395,Maruti Suzuki Swift Dzire Tour (Gat,Maruti,ara),"3,00,000",NaN,NaN
401,URJE,URJENT,SELL,"1,80,000",NaN,NaN
414,Swift Dzire Tour 27 Dec 2016 Regis,Swift,tion,"3,70,000",NaN,NaN
432,Tata zest x,Tata,odel,"3,20,000",NaN,NaN
433,Mahindra xyl,Mahindra,2 bs,"3,50,000",NaN,NaN
441,Used Commercial Maruti Omn,Used,arry,"1,50,000",NaN,NaN
560,Hyun,Hyundai,Eon,Ask For Price,NaN,NaN

Rows where mileage contains 'Petrol':

                          name    company  year     Price kms_driven fuel_type
890   Honda Amaze 1.2 E i VTEC      Honda  2014  1,80,000     Petrol       NaN
891  Chevrolet Sail 1.2 LT ABS  Chevrolet  2014  1,60,000     Petrol       NaN

Numeric summary:

              year         Price     kms_driven
count   842.000000  8.570000e+02     838.000000
mean   2012.523753  4.046885e+05   46010.550119
std       4.024601  4.655365e+05   34469.626299
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   25000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.850000e+05   56437.500000
max    2019.000000  8.500003e+06  400000.000000

In [12]:

# Work on a separate copy; keep df_raw unchanged
df_clean = df_clean.copy()

# 1. Repair the two confirmed fuel-type shifts
shifted_fuel = (
    df_raw["kms_driven"].str.strip().str.lower().eq("petrol")
    & df_raw["fuel_type"].isna()
)

df_clean.loc[shifted_fuel, "fuel_type"] = "Petrol"
df_clean.loc[shifted_fuel, "kms_driven"] = float("nan")

print("Fuel-type records repaired:", shifted_fuel.sum())

# 2. Check for invalid target values
invalid_price = df_clean["Price"].isna() | (df_clean["Price"] <= 0)

# 3. Check for missing or implausible manufacturing years
invalid_year = (
    df_clean["year"].isna()
    | ~df_clean["year"].between(1990, 2026)
)

print("Rows with invalid prices:", invalid_price.sum())
print("Rows with invalid years:", invalid_year.sum())

# 4. Keep records with usable price and year for our first model
df_model = df_clean.loc[
    ~invalid_price & ~invalid_year
].copy()

print("\nOriginal rows:", len(df_raw))
print("Rows available for initial modeling:", len(df_model))
print("Rows excluded:", len(df_raw) - len(df_model))

display(df_model.head())

Fuel-type records repaired: 2
Rows with invalid prices: 35
Rows with invalid years: 50

Original rows: 892
Rows available for initial modeling: 819
Rows excluded: 73

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007.0,80000.0,45000.0,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006.0,425000.0,40.0,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014.0,325000.0,28000.0,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014.0,575000.0,36000.0,Diesel
6,Ford Figo,Ford,2012.0,175000.0,41000.0,Diesel

In [13]:

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression

# Define inputs and target
features = ["company", "year", "kms_driven", "fuel_type"]
target = "Price"

X = df_model[features].copy()
y = df_model[target].copy()

# Separate numeric and categorical columns
numeric_features = ["year", "kms_driven"]
categorical_features = ["company", "fuel_type"]

# Fill missing numeric values using the training-set median
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

# Fill missing categories and convert them into model-readable numbers
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

# Apply the correct processing to each column type
preprocessor = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features)
])

# Reserve test data to evaluate the model on unseen records
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))
print("Input features:", features)
print("Missing values in training features:")
print(X_train.isna().sum())

Training rows: 655
Testing rows: 164
Input features: ['company', 'year', 'kms_driven', 'fuel_type']
Missing values in training features:
company       0
year          0
kms_driven    2
fuel_type     1
dtype: int64

In [14]:

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Build the complete model pipeline
model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", LinearRegression())
])

# Train using only the training data
model.fit(X_train, y_train)

# Predict prices for unseen test records
y_pred = model.predict(X_test)

# Evaluate model performance
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("LINEAR REGRESSION — BASELINE RESULTS")
print(f"MAE:  ₹{mae:,.0f}")
print(f"RMSE: ₹{rmse:,.0f}")
print(f"R²:   {r2:.3f}")

LINEAR REGRESSION — BASELINE RESULTS
MAE:  ₹181,904
RMSE: ₹277,475
R²:   0.531

In [15]:

results = pd.DataFrame({
    "Actual Price": y_test,
    "Predicted Price": y_pred
})

results["Absolute Error"] = (
    results["Actual Price"] - results["Predicted Price"]
).abs()

results["Error %"] = (
    results["Absolute Error"] / results["Actual Price"] * 100
)

display(
    results.sort_values("Absolute Error", ascending=False).head(10)
)

     Actual Price  Predicted Price  Absolute Error     Error %
510     2800000.0    903674.418637    1.896326e+06   67.725914
692     1850000.0    814485.716027    1.035514e+06   55.973745
100     1600000.0    784095.809534    8.159042e+05   50.994012
576      160000.0    776039.214353    6.160392e+05  385.024509
563     1299000.0    733246.596407    5.657534e+05   43.552995
223      275000.0    830724.601403    5.557246e+05  202.081673
875      860000.0    308538.680535    5.514613e+05   64.123409
525     1000000.0    456877.163930    5.431228e+05   54.312284
122      270000.0    764075.735072    4.940757e+05  182.991013
160      169500.0    651270.146475    4.817701e+05  284.230175

In [16]:

from sklearn.model_selection import train_test_split

features_v2 = [
    "name", "company", "year", "kms_driven", "fuel_type"
]

X_v2 = df_model[features_v2].copy()
y_v2 = df_model["Price"].copy()

X_train_v2, X_test_v2, y_train_v2, y_test_v2 = train_test_split(
    X_v2,
    y_v2,
    test_size=0.2,
    random_state=42
)

print("Training rows:", len(X_train_v2))
print("Testing rows:", len(X_test_v2))
print("Features:", features_v2)

Training rows: 655
Testing rows: 164
Features: ['name', 'company', 'year', 'kms_driven', 'fuel_type']

In [17]:

from sklearn.ensemble import RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

numeric_features_v2 = ["year", "kms_driven"]
categorical_features_v2 = ["name", "company", "fuel_type"]

numeric_pipeline_v2 = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_pipeline_v2 = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor_v2 = ColumnTransformer([
    ("numeric", numeric_pipeline_v2, numeric_features_v2),
    ("categorical", categorical_pipeline_v2, categorical_features_v2)
])

rf_model = Pipeline([
    ("preprocessor", preprocessor_v2),
    ("regressor", RandomForestRegressor(
        n_estimators=300,
        min_samples_leaf=2,
        random_state=42,
        n_jobs=-1
    ))
])

rf_model.fit(X_train_v2, y_train_v2)

rf_pred = rf_model.predict(X_test_v2)

rf_mae = mean_absolute_error(y_test_v2, rf_pred)
rf_rmse = np.sqrt(mean_squared_error(y_test_v2, rf_pred))
rf_r2 = r2_score(y_test_v2, rf_pred)

print("RANDOM FOREST RESULTS")
print(f"MAE:  ₹{rf_mae:,.0f}")
print(f"RMSE: ₹{rf_rmse:,.0f}")
print(f"R²:   {rf_r2:.3f}")

RANDOM FOREST RESULTS
MAE:  ₹138,888
RMSE: ₹295,910
R²:   0.467

In [18]:

rf_results = X_test_v2.copy()

rf_results["Actual Price"] = y_test_v2
rf_results["Predicted Price"] = rf_pred

rf_results["Absolute Error"] = (
    rf_results["Actual Price"]
    - rf_results["Predicted Price"]
).abs()

rf_results["Error %"] = (
    rf_results["Absolute Error"]
    / rf_results["Actual Price"] * 100
)

# Show the 10 biggest mistakes
display(
    rf_results.sort_values(
        "Absolute Error",
        ascending=False
    ).head(10).round(2)
)

,name,company,year,kms_driven,fuel_type,Actual Price,Predicted Price,Absolute Error,Error %
510,Jaguar XE XE Portfolio,Jaguar,2016.0,8500.0,Petrol,2800000.0,331586.38,2468413.62,88.16
692,Volvo S80 Summum D4,Volvo,2015.0,42000.0,Diesel,1850000.0,525675.26,1324324.74,71.59
100,BMW 7 Series 740Li Sedan,BMW,2009.0,35000.0,Petrol,1600000.0,576004.16,1023995.84,64.00
698,Mercedes Benz C Class C 220 CDI Avantgarde,Mercedes,2009.0,76000.0,Diesel,1225000.0,251580.86,973419.14,79.46
563,Mahindra XUV500 W10,Mahindra,2018.0,40000.0,Diesel,1299000.0,571703.11,727296.89,55.99
179,Honda City,Honda,2015.0,30000.0,Diesel,599999.0,1244348.64,644349.64,107.39
875,Honda City VX Petrol,Honda,2016.0,95000.0,Petrol,860000.0,295934.18,564065.82,65.59
525,Hyundai Creta 1.6 SX Plus Petrol AT,Hyundai,2016.0,8000.0,Petrol,1000000.0,441074.96,558925.04,55.89
235,Mercedes Benz B Class B180 Sports,Mercedes,2014.0,31000.0,Petrol,1400000.0,858029.27,541970.73,38.71
718,Maruti Suzuki SX4 Celebration Diesel,Maruti,2016.0,85960.0,Diesel,970000.0,505065.62,464934.38,47.93

In [19]:

# Inspect the worst-error cars in the training dataset

cars_to_check = [
    "Jaguar XE XE Portfolio",
    "Volvo S80 Summum D4",
    "BMW 7 Series 740Li Sedan",
    "Mercedes Benz C Class C 220 CDI Avantgarde",
    "Honda City VX Petrol"
]

for car in cars_to_check:
    matches = X_train_v2["name"].eq(car)

    print(f"\n--- {car} ---")
    print("Training examples:", matches.sum())

    if matches.any():
        display(
            pd.concat(
                [
                    X_train_v2.loc[matches],
                    y_train_v2.loc[matches].rename("Actual Price")
                ],
                axis=1
            )
        )
    else:
        print("This exact name was not present in training data.")

--- Jaguar XE XE Portfolio ---
Training examples: 0
This exact name was not present in training data.

--- Volvo S80 Summum D4 ---
Training examples: 0
This exact name was not present in training data.

--- BMW 7 Series 740Li Sedan ---
Training examples: 0
This exact name was not present in training data.

--- Mercedes Benz C Class C 220 CDI Avantgarde ---
Training examples: 0
This exact name was not present in training data.

--- Honda City VX Petrol ---
Training examples: 0
This exact name was not present in training data.

In [20]:

# Count exact car names in the training data
training_name_counts = X_train_v2["name"].value_counts()

# Identify test names that never appeared in training
unseen_mask = ~X_test_v2["name"].isin(training_name_counts.index)

print("Total test records:", len(X_test_v2))
print("Records with unseen car names:", unseen_mask.sum())
print(
    "Percentage of test records with unseen names:",
    round(unseen_mask.mean() * 100, 2),
    "%"
)

print("\nExamples of unseen names:")
display(
    X_test_v2.loc[unseen_mask, ["name", "company", "year"]].head(15)
)

Total test records: 164
Records with unseen car names: 71
Percentage of test records with unseen names: 43.29 %

Examples of unseen names:

                                                 name     company    year
90                    Toyota Corolla Altis Petrol Ltd      Toyota  2009.0
869                         Maruti Suzuki Swift Dzire      Maruti  2016.0
438                             Hyundai i20 Magna 1.2     Hyundai  2010.0
718              Maruti Suzuki SX4 Celebration Diesel      Maruti  2016.0
558                            Chevrolet Cruze LTZ AT   Chevrolet  2014.0
636                         Toyota Innova 2.5 V 7 STR      Toyota  2011.0
833                             Hyundai i20 Magna 1.2     Hyundai  2011.0
358                                Hyundai i10 Sportz     Hyundai  2012.0
525               Hyundai Creta 1.6 SX Plus Petrol AT     Hyundai  2016.0
572  Renault Duster 85PS Diesel RxL Optional with Nav     Renault  2013.0
554                            BMW X1 xDrive20d xLine         BMW  2011.0
675                                     Honda City SV       Honda  2014.0
144                Volkswagen Polo Comfortline 1.2L P  Volkswagen  2015.0
579                               Chevrolet Cruze LTZ   Chevrolet  2011.0
142                  Toyota Innova 2.5 GX BS IV 7 STR      Toyota  2012.0

In [21]:

# First, measure unseen exact names
training_names = set(X_train_v2["name"].unique())
unseen_mask = ~X_test_v2["name"].isin(training_names)

print("Test records:", len(X_test_v2))
print("Unseen exact car names:", int(unseen_mask.sum()))
print("Unseen-name percentage:", round(unseen_mask.mean() * 100, 2), "%")

# Compare models on the same test records
comparison = pd.DataFrame([
    {
        "Model": "Linear Regression (no name)",
        "MAE": mean_absolute_error(y_test, y_pred),
        "RMSE": np.sqrt(mean_squared_error(y_test, y_pred)),
        "R2": r2_score(y_test, y_pred)
    },
    {
        "Model": "Linear Regression (with name)",
        "MAE": mean_absolute_error(
            y_test_v2,
            # Train a separate linear model using X_train_v2
            Pipeline([
                ("preprocessor", preprocessor_v2),
                ("regressor", LinearRegression())
            ]).fit(X_train_v2, y_train_v2).predict(X_test_v2)
        ),
        "RMSE": np.nan,
        "R2": np.nan
    }
])

# Fill in the full metrics for the second model
lr_name_model = Pipeline([
    ("preprocessor", preprocessor_v2),
    ("regressor", LinearRegression())
])
lr_name_model.fit(X_train_v2, y_train_v2)
lr_name_pred = lr_name_model.predict(X_test_v2)

comparison.loc[1, "RMSE"] = np.sqrt(
    mean_squared_error(y_test_v2, lr_name_pred)
)
comparison.loc[1, "R2"] = r2_score(y_test_v2, lr_name_pred)

comparison.loc[len(comparison)] = {
    "Model": "Random Forest (with name)",
    "MAE": mean_absolute_error(y_test_v2, rf_pred),
    "RMSE": np.sqrt(mean_squared_error(y_test_v2, rf_pred)),
    "R2": r2_score(y_test_v2, rf_pred)
}

display(comparison.round(3))

Test records: 164
Unseen exact car names: 71
Unseen-name percentage: 43.29 %

                           Model         MAE        RMSE     R2
0    Linear Regression (no name)  181904.192  277475.164  0.531
1  Linear Regression (with name)  172499.013  268262.808  0.562
2      Random Forest (with name)  138887.867  295909.657  0.467

In [22]:

import re

def extract_model_family(row):
    name = str(row["name"]).strip()
    company = str(row["company"]).strip()

    # Remove the manufacturer prefix when it appears in the name
    name_lower = name.lower()
    company_lower = company.lower()

    if name_lower.startswith(company_lower):
        name = name[len(company):].strip()

    # First remaining token is a starting approximation
    # We'll improve this rule after inspecting the results.
    tokens = re.findall(r"[A-Za-z0-9]+", name)

    return tokens[0].lower() if tokens else "unknown"


df_model["model_family"] = df_model.apply(
    extract_model_family, axis=1
)

print("Unique exact car names:", df_model["name"].nunique())
print("Unique extracted families:", df_model["model_family"].nunique())

display(
    df_model[["name", "company", "model_family"]].head(20)
)

Unique exact car names: 465
Unique extracted families: 105

                                      name   company model_family
0     Hyundai Santro Xing XO eRLX Euro III   Hyundai       santro
1                  Mahindra Jeep CL550 MDI  Mahindra         jeep
3   Hyundai Grand i10 Magna 1.2 Kappa VTVT   Hyundai        grand
4         Ford EcoSport Titanium 1.5L TDCi      Ford     ecosport
6                                Ford Figo      Ford         figo
7                              Hyundai Eon   Hyundai          eon
8         Ford EcoSport Ambiente 1.5L TDCi      Ford     ecosport
9           Maruti Suzuki Alto K10 VXi AMT    Maruti       suzuki
10             Skoda Fabia Classic 1.2 MPI     Skoda        fabia
11              Maruti Suzuki Stingray VXi    Maruti       suzuki
12             Hyundai Elite i20 Magna 1.2   Hyundai        elite
13              Mahindra Scorpio SLE BS IV  Mahindra      scorpio
14    Hyundai Santro Xing XO eRLX Euro III   Hyundai       santro
15                 Mahindra Jeep CL550 MDI  Mahindra         jeep
16                                 Audi A8      Audi           a8
17                                 Audi Q7      Audi           q7
18                    Mahindra Scorpio S10  Mahindra      scorpio
19                  Maruti Suzuki Alto 800    Maruti       suzuki
20                    Mahindra Scorpio S10  Mahindra      scorpio
21                    Mahindra Scorpio S10  Mahindra      scorpio

In [23]:

import re

def extract_model_family(row):
    name = str(row["name"]).lower().strip()
    company = str(row["company"]).lower().strip()

    # Remove manufacturer prefix from the beginning of the name
    if name.startswith(company):
        name = name[len(company):].strip()

    # Remove "suzuki" when it follows the Maruti prefix
    if company == "maruti" and name.startswith("suzuki "):
        name = name[len("suzuki "):].strip()

    # Match known multiword model families first
    known_families = [
        "grand i10", "elite i20", "swift dzire",
        "alto k10", "alto 800", "swift", "dzire",
        "i10", "i20", "city", "amaze", "creta",
        "scorpio", "xuv500", "bolero", "santro",
        "ecosport", "figo", "duster", "innova",
        "corolla", "polo", "vento", "cruze",
        "sail", "zest", "indigo", "nano", "tiago",
        "brio", "jazz", "etios", "fortuner"
    ]

    for family in known_families:
        if re.search(r"\b" + re.escape(family) + r"\b", name):
            return family

    # Fallback for names not covered by the initial dictionary
    tokens = re.findall(r"[a-z0-9]+", name)
    return tokens[0] if tokens else "unknown"


df_model["model_family"] = df_model.apply(
    extract_model_family, axis=1
)

print("Unique exact car names:", df_model["name"].nunique())
print("Unique extracted model families:", df_model["model_family"].nunique())

display(
    df_model[["name", "company", "model_family"]].head(30)
)

Unique exact car names: 465
Unique extracted model families: 129

                                      name   company model_family
0     Hyundai Santro Xing XO eRLX Euro III   Hyundai       santro
1                  Mahindra Jeep CL550 MDI  Mahindra         jeep
3   Hyundai Grand i10 Magna 1.2 Kappa VTVT   Hyundai    grand i10
4         Ford EcoSport Titanium 1.5L TDCi      Ford     ecosport
6                                Ford Figo      Ford         figo
7                              Hyundai Eon   Hyundai          eon
8         Ford EcoSport Ambiente 1.5L TDCi      Ford     ecosport
9           Maruti Suzuki Alto K10 VXi AMT    Maruti     alto k10
10             Skoda Fabia Classic 1.2 MPI     Skoda        fabia
11              Maruti Suzuki Stingray VXi    Maruti     stingray
12             Hyundai Elite i20 Magna 1.2   Hyundai    elite i20
13              Mahindra Scorpio SLE BS IV  Mahindra      scorpio
14    Hyundai Santro Xing XO eRLX Euro III   Hyundai       santro
15                 Mahindra Jeep CL550 MDI  Mahindra         jeep
16                                 Audi A8      Audi           a8
17                                 Audi Q7      Audi           q7
18                    Mahindra Scorpio S10  Mahindra      scorpio
19                  Maruti Suzuki Alto 800    Maruti     alto 800
20                    Mahindra Scorpio S10  Mahindra      scorpio
21                    Mahindra Scorpio S10  Mahindra      scorpio
22              Maruti Suzuki Alto 800 Vxi    Maruti     alto 800
23                  Hyundai i20 Sportz 1.2   Hyundai          i20
24                  Hyundai i20 Sportz 1.2   Hyundai          i20
25                  Hyundai i20 Sportz 1.2   Hyundai          i20
26               Maruti Suzuki Alto 800 Lx    Maruti     alto 800
27         Maruti Suzuki Vitara Brezza ZDi    Maruti       vitara
28                   Maruti Suzuki Alto LX    Maruti         alto
29                      Mahindra Bolero DI  Mahindra       bolero
30           Maruti Suzuki Swift Dzire ZDi    Maruti  swift dzire
31                Mahindra Scorpio S10 4WD  Mahindra      scorpio

In [24]:

# Add the family feature to our existing train/test split
X_train_family = X_train_v2.copy()
X_test_family = X_test_v2.copy()

X_train_family["model_family"] = df_model.loc[
    X_train_family.index, "model_family"
]
X_test_family["model_family"] = df_model.loc[
    X_test_family.index, "model_family"
]

numeric_features = ["year", "kms_driven"]
categorical_features = [
    "name", "company", "fuel_type", "model_family"
]

preprocessor_family = ColumnTransformer([
    (
        "numeric",
        Pipeline([
            ("imputer", SimpleImputer(strategy="median"))
        ]),
        numeric_features
    ),
    (
        "categorical",
        Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("encoder", OneHotEncoder(handle_unknown="ignore"))
        ]),
        categorical_features
    )
])

family_model = Pipeline([
    ("preprocessor", preprocessor_family),
    ("regressor", LinearRegression())
])

family_model.fit(X_train_family, y_train_v2)
family_pred = family_model.predict(X_test_family)

family_mae = mean_absolute_error(y_test_v2, family_pred)
family_rmse = np.sqrt(mean_squared_error(y_test_v2, family_pred))
family_r2 = r2_score(y_test_v2, family_pred)

print("LINEAR REGRESSION — WITH MODEL FAMILY")
print(f"MAE:  ₹{family_mae:,.0f}")
print(f"RMSE: ₹{family_rmse:,.0f}")
print(f"R²:   {family_r2:.3f}")

LINEAR REGRESSION — WITH MODEL FAMILY
MAE:  ₹151,072
RMSE: ₹257,325
R²:   0.597

In [25]:

final_comparison = pd.DataFrame([
    {
        "Model": "Linear Regression — no name",
        "MAE": 181904.192,
        "RMSE": 277475.164,
        "R2": 0.531
    },
    {
        "Model": "Linear Regression — name",
        "MAE": 172499.013,
        "RMSE": 268262.808,
        "R2": 0.562
    },
    {
        "Model": "Random Forest — name",
        "MAE": 138887.867,
        "RMSE": 295909.657,
        "R2": 0.467
    },
    {
        "Model": "Linear Regression — name + family",
        "MAE": family_mae,
        "RMSE": family_rmse,
        "R2": family_r2
    }
])

display(
    final_comparison.sort_values("MAE").reset_index(drop=True).round(3)
)

                               Model         MAE        RMSE     R2
0               Random Forest — name  138887.867  295909.657  0.467
1  Linear Regression — name + family  151071.914  257324.888  0.597
2           Linear Regression — name  172499.013  268262.808  0.562
3        Linear Regression — no name  181904.192  277475.164  0.531

In [26]:

from sklearn.model_selection import KFold, cross_validate
from sklearn.base import clone

# Use only training data for model selection
cv = KFold(n_splits=5, shuffle=True, random_state=42)

# Compare Linear Regression with name + family
family_cv_model = clone(family_model)

cv_results = cross_validate(
    family_cv_model,
    X_train_family,
    y_train_v2,
    cv=cv,
    scoring={
        "mae": "neg_mean_absolute_error",
        "rmse": "neg_root_mean_squared_error",
        "r2": "r2"
    },
    n_jobs=-1
)

cv_mae = -cv_results["test_mae"]
cv_rmse = -cv_results["test_rmse"]
cv_r2 = cv_results["test_r2"]

print("5-FOLD CROSS-VALIDATION — LINEAR REGRESSION")
print(f"Mean MAE:  ₹{cv_mae.mean():,.0f}")
print(f"MAE std:   ₹{cv_mae.std():,.0f}")
print(f"Mean RMSE: ₹{cv_rmse.mean():,.0f}")
print(f"RMSE std:  ₹{cv_rmse.std():,.0f}")
print(f"Mean R²:   {cv_r2.mean():.3f}")
print(f"R² std:    {cv_r2.std():.3f}")

5-FOLD CROSS-VALIDATION — LINEAR REGRESSION
Mean MAE:  ₹157,872
MAE std:   ₹12,536
Mean RMSE: ₹340,172
RMSE std:  ₹183,493
Mean R²:   0.495
R² std:    0.174

In [27]:

import pandas as pd

fold_results = pd.DataFrame({
    "Fold": range(1, 6),
    "MAE": cv_mae,
    "RMSE": cv_rmse,
    "R2": cv_r2
})

display(
    fold_results.style.format({
        "MAE": "₹{:,.0f}",
        "RMSE": "₹{:,.0f}",
        "R2": "{:.3f}"
    })
)

In [28]:

from sklearn.model_selection import KFold
from sklearn.base import clone
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
import pandas as pd

# Re-create the exact five folds used in cross-validation
cv = KFold(n_splits=5, shuffle=True, random_state=42)
splits = list(cv.split(X_train_family, y_train_v2))

# Select Fold 5 (Python uses zero-based indexing)
train_idx, val_idx = splits[4]

X_fold_train = X_train_family.iloc[train_idx]
X_fold_val = X_train_family.iloc[val_idx]

y_fold_train = y_train_v2.iloc[train_idx]
y_fold_val = y_train_v2.iloc[val_idx]

# Train a fresh copy of our pipeline
fold5_model = clone(family_model)
fold5_model.fit(X_fold_train, y_fold_train)

fold5_pred = fold5_model.predict(X_fold_val)

# Inspect actual vs predicted prices
fold5_results = pd.DataFrame({
    "Car": X_fold_val["name"],
    "Company": X_fold_val["company"],
    "Year": X_fold_val["year"],
    "Actual_Price": y_fold_val,
    "Predicted_Price": fold5_pred
})

fold5_results["Absolute_Error"] = (
    fold5_results["Actual_Price"] -
    fold5_results["Predicted_Price"]
).abs()

fold5_results = fold5_results.sort_values(
    "Absolute_Error", ascending=False
)

display(
    fold5_results.head(15).style.format({
        "Actual_Price": "₹{:,.0f}",
        "Predicted_Price": "₹{:,.0f}",
        "Absolute_Error": "₹{:,.0f}"
    })
)

print("Fold 5 records:", len(fold5_results))
print("MAE:", round(mean_absolute_error(y_fold_val, fold5_pred)))
print("RMSE:", round(np.sqrt(mean_squared_error(y_fold_val, fold5_pred))))
print("R²:", round(r2_score(y_fold_val, fold5_pred), 3))

Fold 5 records: 131
MAE: 181449
RMSE: 702917
R²: 0.161

In [29]:
# How much do the largest errors contribute to Fold 5's squared error?
errors = fold5_results.sort_values(
    "Absolute_Error", ascending=False
).copy()

errors["Squared_Error"] = errors["Absolute_Error"] ** 2

total_squared_error = errors["Squared_Error"].sum()

print("Top 5 cars' share of total squared error:",
      f"{errors.head(5)['Squared_Error'].sum() / total_squared_error:.1%}")

print("\nTop 15 largest prediction errors:")
display(errors[
    ["Car", "Company", "Year", "Actual_Price",
     "Predicted_Price", "Absolute_Error"]
].head(15).style.format({
    "Actual_Price": "₹{:,.0f}",
    "Predicted_Price": "₹{:,.0f}",
    "Absolute_Error": "₹{:,.0f}"
}))

Top 5 cars' share of total squared error: 96.0%

Top 15 largest prediction errors:

In [30]:

# Inspect the original data before cleaning
suspicious_cars = [
    "Mahindra XUV500 W6",
    "Audi Q7",
    "Honda City ZX CVT",
    "Tata Indica eV2 LS"
]

display(
    df_raw.loc[
        df_raw["name"].astype(str).str.strip().isin(suspicious_cars),
        ["name", "company", "year", "Price", "kms_driven", "fuel_type"]
    ].sort_values("name")
)

                   name   company  year          Price  kms_driven fuel_type
17              Audi Q7      Audi  2014       5,00,000  16,934 kms    Diesel
58    Honda City ZX CVT     Honda  2017       1,70,000  15,000 kms    Diesel
484  Mahindra XUV500 W6  Mahindra  2013       5,48,900  49,800 kms    Diesel
562  Mahindra XUV500 W6  Mahindra  2014      85,00,003  45,000 kms    Diesel
586  Mahindra XUV500 W6  Mahindra  2013       5,49,900  52,800 kms    Diesel
304  Tata Indica eV2 LS      Tata  2017  Ask For Price  84,000 kms    Diesel
666  Tata Indica eV2 LS      Tata  2015       1,40,000  60,105 kms    Diesel
864  Tata Indica eV2 LS      Tata  2016         50,500  91,200 kms    Diesel

In [31]:

# Document the suspicious record
suspicious_xuv_mask = (
    df_model["name"].eq("Mahindra XUV500 W6")
    & df_model["year"].eq(2014)
    & df_model["Price"].eq(8500003)
)

print("Suspicious rows found:", suspicious_xuv_mask.sum())

# Create a modeling dataset without the suspicious listing
df_model_v2 = df_model.loc[~suspicious_xuv_mask].copy()

print("Original modeling rows:", len(df_model))
print("Rows after exclusion:", len(df_model_v2))
print("Excluded rows:", len(df_model) - len(df_model_v2))

Suspicious rows found: 1
Original modeling rows: 819
Rows after exclusion: 818
Excluded rows: 1

In [32]:

from sklearn.model_selection import train_test_split

# Rebuild features and target using the updated dataset
features = ["name", "company", "year", "kms_driven", "fuel_type"]
target = "Price"

X = df_model_v2[features].copy()
y = df_model_v2[target].copy()

# Create a fresh train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Total rows:", len(df_model_v2))
print("Training rows:", len(X_train))
print("Test rows:", len(X_test))

Total rows: 818
Training rows: 654
Test rows: 164

In [33]:

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression

numeric_features = ["year", "kms_driven"]
categorical_features = ["name", "company", "fuel_type"]

preprocessor = ColumnTransformer([
    ("numeric", Pipeline([
        ("imputer", SimpleImputer(strategy="median"))
    ]), numeric_features),

    ("categorical", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ]), categorical_features)
])

model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", LinearRegression())
])

model.fit(X_train, y_train)

print("Fresh model trained successfully!")

Fresh model trained successfully!

In [34]:

from sklearn.model_selection import KFold, cross_validate
import numpy as np

cv = KFold(n_splits=5, shuffle=True, random_state=42)

cv_results = cross_validate(
    model,
    X_train,
    y_train,
    cv=cv,
    scoring={
        "mae": "neg_mean_absolute_error",
        "rmse": "neg_root_mean_squared_error",
        "r2": "r2"
    },
    n_jobs=-1
)

cv_mae = -cv_results["test_mae"]
cv_rmse = -cv_results["test_rmse"]
cv_r2 = cv_results["test_r2"]

print("5-FOLD CROSS-VALIDATION — UPDATED DATASET")
print(f"Mean MAE:  ₹{cv_mae.mean():,.0f}")
print(f"Mean RMSE: ₹{cv_rmse.mean():,.0f}")
print(f"Mean R²:   {cv_r2.mean():.3f}")

fold_results = pd.DataFrame({
    "Fold": range(1, 6),
    "MAE": cv_mae,
    "RMSE": cv_rmse,
    "R2": cv_r2
})

display(fold_results.round(3))

5-FOLD CROSS-VALIDATION — UPDATED DATASET
Mean MAE:  ₹143,416
Mean RMSE: ₹242,328
Mean R²:   0.589

   Fold         MAE        RMSE     R2
0     1  113767.803  165106.569  0.606
1     2  136834.743  226652.050  0.697
2     3  150370.793  236542.286  0.567
3     4  168299.724  278003.746  0.656
4     5  147807.018  305336.000  0.416

In [36]:

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
import numpy as np

# Predict prices for the held-out test set
test_predictions = model.predict(X_test)

# Calculate evaluation metrics
test_mae = mean_absolute_error(y_test, test_predictions)
test_rmse = np.sqrt(mean_squared_error(y_test, test_predictions))
test_r2 = r2_score(y_test, test_predictions)

print("FINAL HOLDOUT TEST RESULTS")
print(f"MAE:  ₹{test_mae:,.0f}")
print(f"RMSE: ₹{test_rmse:,.0f}")
print(f"R²:   {test_r2:.3f}")

FINAL HOLDOUT TEST RESULTS
MAE:  ₹132,889
RMSE: ₹194,102
R²:   0.679

In [37]:

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, KFold, cross_validate
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

# Re-create model-family feature on the updated dataset
df_model_v2 = df_model_v2.copy()
df_model_v2["model_family"] = df_model_v2.apply(
    extract_model_family, axis=1
)

# Common target
y = df_model_v2["Price"].copy()

# Model A: car name, company, year, mileage and fuel
base_features = ["name", "company", "year", "kms_driven", "fuel_type"]
X_base = df_model_v2[base_features].copy()

# Model B/C: add model family
family_features = base_features + ["model_family"]
X_family = df_model_v2[family_features].copy()

# One common split for every model
X_train_base, X_test_base, y_train, y_test = train_test_split(
    X_base, y, test_size=0.2, random_state=42
)

X_train_family = X_family.loc[X_train_base.index]
X_test_family = X_family.loc[X_test_base.index]

print("Training rows:", len(X_train_base))
print("Test rows:", len(X_test_base))
print("Model-family feature ready.")

Training rows: 654
Test rows: 164
Model-family feature ready.

In [38]:

def build_car_pipeline(use_family=False, algorithm="linear"):

    numeric_features = ["year", "kms_driven"]

    categorical_features = ["name", "company", "fuel_type"]
    if use_family:
        categorical_features.append("model_family")

    preprocessor = ColumnTransformer([
        ("numeric", Pipeline([
            ("imputer", SimpleImputer(strategy="median"))
        ]), numeric_features),

        ("categorical", Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("encoder", OneHotEncoder(handle_unknown="ignore"))
        ]), categorical_features)
    ])

    if algorithm == "linear":
        regressor = LinearRegression()
    else:
        regressor = RandomForestRegressor(
            n_estimators=300,
            min_samples_leaf=2,
            random_state=42,
            n_jobs=1
        )

    return Pipeline([
        ("preprocessor", preprocessor),
        ("regressor", regressor)
    ])


models = {
    "Linear Regression — name": build_car_pipeline(
        use_family=False, algorithm="linear"
    ),
    "Linear Regression — name + family": build_car_pipeline(
        use_family=True, algorithm="linear"
    ),
    "Random Forest — name + family": build_car_pipeline(
        use_family=True, algorithm="forest"
    )
}

print("All three candidate pipelines created.")

All three candidate pipelines created.

In [39]:

cv = KFold(n_splits=5, shuffle=True, random_state=42)

results = []

for model_name, candidate in models.items():

    if "family" in model_name:
        X_for_cv = X_train_family
    else:
        X_for_cv = X_train_base

    scores = cross_validate(
        candidate,
        X_for_cv,
        y_train,
        cv=cv,
        scoring={
            "mae": "neg_mean_absolute_error",
            "rmse": "neg_root_mean_squared_error",
            "r2": "r2"
        },
        n_jobs=-1
    )

    results.append({
        "Model": model_name,
        "Mean MAE": -scores["test_mae"].mean(),
        "Mean RMSE": -scores["test_rmse"].mean(),
        "Mean R2": scores["test_r2"].mean(),
        "MAE Std": scores["test_mae"].std()
    })

comparison = pd.DataFrame(results).sort_values("Mean RMSE")

display(comparison.style.format({
    "Mean MAE": "₹{:,.0f}",
    "Mean RMSE": "₹{:,.0f}",
    "Mean R2": "{:.3f}",
    "MAE Std": "₹{:,.0f}"
}))

In [40]:

# Select our candidate
best_model = models["Linear Regression — name + family"]

# Fit using the complete training set
best_model.fit(X_train_family, y_train)

# Evaluate once on the holdout set
final_predictions = best_model.predict(X_test_family)

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
import numpy as np

final_mae = mean_absolute_error(y_test, final_predictions)
final_rmse = np.sqrt(mean_squared_error(y_test, final_predictions))
final_r2 = r2_score(y_test, final_predictions)

print("SELECTED MODEL — HOLDOUT TEST RESULTS")
print(f"MAE:  ₹{final_mae:,.0f}")
print(f"RMSE: ₹{final_rmse:,.0f}")
print(f"R²:   {final_r2:.3f}")

SELECTED MODEL — HOLDOUT TEST RESULTS
MAE:  ₹115,003
RMSE: ₹174,021
R²:   0.742

In [41]:

error_analysis = pd.DataFrame({
    "Car": X_test_family["name"],
    "Company": X_test_family["company"],
    "Year": X_test_family["year"],
    "Actual_Price": y_test,
    "Predicted_Price": final_predictions
})

error_analysis["Absolute_Error"] = (
    error_analysis["Actual_Price"] -
    error_analysis["Predicted_Price"]
).abs()

display(
    error_analysis.sort_values(
        "Absolute_Error", ascending=False
    ).head(10).style.format({
        "Actual_Price": "₹{:,.0f}",
        "Predicted_Price": "₹{:,.0f}",
        "Absolute_Error": "₹{:,.0f}"
    })
)

In [42]:

negative_mask = final_predictions < 0

print("Test records:", len(final_predictions))
print("Negative predictions:", negative_mask.sum())
print(
    "Percentage negative:",
    f"{negative_mask.mean() * 100:.2f}%"
)

print("\nLowest predictions:")
display(
    error_analysis.nsmallest(10, "Predicted_Price")[
        ["Car", "Actual_Price", "Predicted_Price"]
    ]
)

Test records: 164
Negative predictions: 6
Percentage negative: 3.66%

Lowest predictions:

,Car,Actual_Price,Predicted_Price
820,Maruti Suzuki Alto 800 Lx,70000.0,-124669.311953
255,Maruti Suzuki Wagon R 1.0,90000.0,-84517.639245
851,Maruti Suzuki 800 Std BS III,30000.0,-72452.159848
821,Maruti Suzuki Alto,100000.0,-71050.153698
553,Tata Indica V2 DLG,35000.0,-59570.880737
768,Hindustan Motors Ambassador Classic Mark 4 – Befo,750000.0,-20624.036348
226,Maruti Suzuki Wagon R LX BS III,80000.0,1362.746664
469,Toyota Corolla H2,150000.0,10990.882595
375,Maruti Suzuki Zen LXi BS III,85000.0,11483.565731
839,Tata Indica V2,39999.0,11515.905945

In [44]:
import numpy as np
from sklearn.compose import TransformedTargetRegressor

log_price_model = TransformedTargetRegressor(
    regressor=build_car_pipeline(
        use_family=True,
        algorithm="linear"
    ),
    func=np.log1p,
    inverse_func=np.expm1
)

print("Log-price model created successfully!")

Log-price model created successfully!

In [46]:
log_scores = cross_validate(
    log_price_model,
    X_train_family,
    y_train,
    cv=cv,
    scoring={
        "mae": "neg_mean_absolute_error",
        "rmse": "neg_root_mean_squared_error",
        "r2": "r2"
    },
    n_jobs=-1
)

print("LOG-PRICE MODEL — 5-FOLD CV")
print(f"Mean MAE:  ₹{-log_scores['test_mae'].mean():,.0f}")
print(f"Mean RMSE: ₹{-log_scores['test_rmse'].mean():,.0f}")
print(f"Mean R²:   {log_scores['test_r2'].mean():.3f}")

LOG-PRICE MODEL — 5-FOLD CV
Mean MAE:  ₹117,549
Mean RMSE: ₹249,053
Mean R²:   0.583

In [47]:
import numpy as np
from sklearn.compose import TransformedTargetRegressor

log_price_model = TransformedTargetRegressor(
    regressor=build_car_pipeline(
        use_family=True,
        algorithm="linear"
    ),
    func=np.log1p,
    inverse_func=np.expm1
)

print("Log-price model created successfully!")

Log-price model created successfully!

In [48]:
log_scores = cross_validate(
    log_price_model,
    X_train_family,
    y_train,
    cv=cv,
    scoring={
        "mae": "neg_mean_absolute_error",
        "rmse": "neg_root_mean_squared_error",
        "r2": "r2"
    },
    n_jobs=-1
)

print("LOG-PRICE MODEL — 5-FOLD CV")
print(f"Mean MAE:  ₹{-log_scores['test_mae'].mean():,.0f}")
print(f"Mean RMSE: ₹{-log_scores['test_rmse'].mean():,.0f}")
print(f"Mean R²:   {log_scores['test_r2'].mean():.3f}")

LOG-PRICE MODEL — 5-FOLD CV
Mean MAE:  ₹117,549
Mean RMSE: ₹249,053
Mean R²:   0.583

In [49]:

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
import numpy as np
import pandas as pd

# Fit both candidates on identical training rows
best_model.fit(X_train_family, y_train)
log_price_model.fit(X_train_family, y_train)

# Predict on the same held-out test rows
regular_pred = best_model.predict(X_test_family)
log_pred = log_price_model.predict(X_test_family)

def evaluate_predictions(actual, predicted, model_name):
    return {
        "Model": model_name,
        "MAE": mean_absolute_error(actual, predicted),
        "RMSE": np.sqrt(mean_squared_error(actual, predicted)),
        "R2": r2_score(actual, predicted),
        "Negative predictions": int((predicted < 0).sum())
    }

test_comparison = pd.DataFrame([
    evaluate_predictions(
        y_test, regular_pred, "Linear Regression + family"
    ),
    evaluate_predictions(
        y_test, log_pred, "Log-price + family"
    )
])

display(test_comparison.style.format({
    "MAE": "₹{:,.0f}",
    "RMSE": "₹{:,.0f}",
    "R2": "{:.3f}"
}))

In [50]:

# Apply a non-negative output safeguard
regular_pred_clipped = np.maximum(regular_pred, 0)

comparison_clipped = pd.DataFrame([
    evaluate_predictions(
        y_test, regular_pred, "Linear Regression — original"
    ),
    evaluate_predictions(
        y_test, regular_pred_clipped, "Linear Regression — clipped"
    ),
    evaluate_predictions(
        y_test, log_pred, "Log-price Regression"
    )
])

display(comparison_clipped.style.format({
    "MAE": "₹{:,.0f}",
    "RMSE": "₹{:,.0f}",
    "R2": "{:.3f}"
}))

In [51]:

from pathlib import Path
import joblib
import numpy as np

# Project's model output folder
model_dir = Path("../models")
model_dir.mkdir(parents=True, exist_ok=True)

# Fit the selected model on the training data
final_model = models["Linear Regression — name + family"]
final_model.fit(X_train_family, y_train)

# Save the full fitted pipeline
model_path = model_dir / "car_price_model.joblib"
joblib.dump(final_model, model_path)

print("Model saved to:", model_path.resolve())
print("File exists:", model_path.exists())

Model saved to: D:\Product Management\Koushik-Projects\AI-ML-Experiments\car-price-prediction\models\car_price_model.joblib
File exists: True

In [52]:

import json

metadata = {
    "model_name": "Linear Regression with model family",
    "target": "Price",
    "features": [
        "name",
        "company",
        "year",
        "kms_driven",
        "fuel_type",
        "model_family"
    ],
    "output_safeguard": "Flag negative predictions; clip to zero only as a fallback",
    "notes": [
        "Trained on the cleaned Quikr car dataset.",
        "One suspicious price record was excluded.",
        "Evaluation scores are exploratory because the holdout set was reused."
    ]
}

metadata_path = model_dir / "model_metadata.json"

with open(metadata_path, "w", encoding="utf-8") as file:
    json.dump(metadata, file, indent=2)

print("Metadata saved to:", metadata_path.resolve())

Metadata saved to: D:\Product Management\Koushik-Projects\AI-ML-Experiments\car-price-prediction\models\model_metadata.json

In [53]:
from pathlib import Path

model_dir = Path("../models")

for filename in ["car_price_model.joblib", "model_metadata.json"]:
    file_path = model_dir / filename
    print(
        f"{filename}:",
        "✅ Exists" if file_path.exists() else "❌ Missing"
    )

car_price_model.joblib: ✅ Exists
model_metadata.json: ✅ Exists

In [54]:
from pathlib import Path

print("Current folder:", Path.cwd())

Current folder: d:\Product Management\Koushik-Projects\AI-ML-Experiments\car-price-prediction\notebooks

In [55]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
sys.path.insert(0, str(project_root))

from src.predict import predict_car_price

result = predict_car_price(
    name="Maruti Suzuki Swift Dzire VDI",
    company="Maruti",
    year=2016,
    kms_driven=65000,
    fuel_type="Diesel"
)

print(result)

{'predicted_price': 431533.76, 'raw_prediction': 431533.76, 'requires_review': False}

In [56]:
from pathlib import Path

predict_path = Path.cwd().parent / "src" / "predict.py"

print("File:", predict_path)
print("\n--- predict.py contents ---")
print(predict_path.read_text(encoding="utf-8"))

File: d:\Product Management\Koushik-Projects\AI-ML-Experiments\car-price-prediction\src\predict.py

--- predict.py contents ---

from pathlib import Path
import joblib
import pandas as pd

from src.model_features import extract_model_family

PROJECT_ROOT = Path(__file__).resolve().parents[1]
MODEL_PATH = PROJECT_ROOT / "models" / "car_price_model.joblib"

model = joblib.load(MODEL_PATH)


def predict_car_price(
    name: str,
    company: str,
    year: int,
    kms_driven: float,
    fuel_type: str
) -> dict:
    """Predict a used car's price and flag unrealistic raw outputs."""

    model_family = extract_model_family({
        "name": name,
        "company": company
    })

    car = pd.DataFrame([{
        "name": name,
        "company": company,
        "year": year,
        "kms_driven": kms_driven,
        "fuel_type": fuel_type,
        "model_family": model_family
    }])

    raw_prediction = float(model.predict(car)[0])
    was_negative = raw_prediction < 0

    # Fallback only; a zero price is not a reliable valuation.
    displayed_prediction = max(0.0, raw_prediction)

    return {
        "predicted_price": round(displayed_prediction, 2),
        "raw_prediction": round(raw_prediction, 2),
        "requires_review": was_negative
    }

In [57]:
import importlib
import src.predict

importlib.reload(src.predict)

print("Function available:", hasattr(src.predict, "predict_car_price"))

Function available: True

In [58]:
from src.predict import predict_car_price

result = predict_car_price(
    name="Maruti Suzuki Swift Dzire VDI",
    company="Maruti",
    year=2016,
    kms_driven=65000,
    fuel_type="Diesel"
)

print(result)

{'predicted_price': 431533.76, 'raw_prediction': 431533.76, 'requires_review': False}

In [59]:
import pandas as pd
from pathlib import Path

DATA_PATH = Path("../data/quikr_car.csv")

df = pd.read_csv(DATA_PATH)

print("Dataset loaded successfully!")
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

display(df.head())

Dataset loaded successfully!
Shape: (892, 6)
Columns: ['name', 'company', 'year', 'Price', 'kms_driven', 'fuel_type']

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [60]:
company = df["company"].astype("string").str.strip()

suspicious = (
    company.isna()
    | company.eq("")
    | company.str.fullmatch(r"\d+", na=False)
    | company.str.lower().isin(
        ["any", "nan", "none", "null", "unknown"]
    )
)

print("Suspicious rows:", suspicious.sum())

display(
    df.loc[suspicious, ["name", "company", "year", "Price"]]
)

Suspicious rows: 4

                                       name company  year          Price
792                   2012 Tata Sumo Gold f    2012  sell       2,50,000
798   7 SEATER MAHINDRA BOLERO IN VERY GOOD       7  D...  Ask For Price
799                   9 SEATER MAHINDRA BOL       9  , Ac  Ask For Price
845  Any type car avaiabel hare...comercica     Any  r...       1,70,000

In [61]:
display(
    df.loc[
        [792, 798, 799, 845],
        ["name", "company", "year", "Price", "kms_driven", "fuel_type"]
    ].to_string()
)

'                                       name company  year          Price kms_driven fuel_type\n792                   2012 Tata Sumo Gold f    2012  sell       2,50,000        NaN       NaN\n798   7 SEATER MAHINDRA BOLERO IN VERY GOOD       7  D...  Ask For Price        NaN       NaN\n799                   9 SEATER MAHINDRA BOL       9  , Ac  Ask For Price        NaN       NaN\n845  Any type car avaiabel hare...comercica     Any  r...       1,70,000        NaN       NaN'

In [62]:
display(df.loc[788:802])
display(df.loc[840:848])

,name,company,year,Price,kms_driven,fuel_type
788,Maruti Suzuki Swift LDi,Maruti,2009,"1,20,000","90,000 kms",Diesel
789,Maruti Suzuki Swift VDi,Maruti,2009,"1,20,000","90,000 kms",Diesel
790,Tata Indigo eCS,Tata,2016,"1,30,000","1,50,000 kms",Diesel
791,Chevrolet Beat LS Diesel,Chevrolet,2014,"1,89,000","31,000 kms",Diesel
792,2012 Tata Sumo Gold f,2012,sell,"2,50,000",NaN,NaN
793,Mahindra Xylo E8 BS IV,Mahindra,2011,"3,65,000","43,000 kms",Diesel
794,Hyundai Eon D Lite Plus,Hyundai,2013,"1,70,000","20,000 kms",Petrol
795,Well mentained Tata Sumo,Well,d Ex,"3,80,000",NaN,NaN
796,all paper updated tata indica v2 and u,all,n...,"1,45,000",NaN,NaN
797,Maruti Ertiga showroom condition with,Maruti,e...,"4,80,000",NaN,NaN
798,7 SEATER MAHINDRA BOLERO IN VERY GOOD,7,D...,Ask For Price,NaN,NaN
799,9 SEATER MAHINDRA BOL,9,", Ac",Ask For Price,NaN,NaN
800,scratch less Tata I,scratch,go .,"1,40,000",NaN,NaN
801,Maruti Suzuki swift dzire for sale in,Maruti,d...,"3,60,000",NaN,NaN
802,Commercial Chevrolet beat for sale in,Commercial,k...,"1,80,000",NaN,NaN

,name,company,year,Price,kms_driven,fuel_type
840,Hyundai Santro Xing GL,Hyundai,2006,"85,000","60,000 kms",Petrol
841,Maruti Suzuki Wagon R 1.0 VXi,Maruti,2016,"3,95,000","20,000 kms",Petrol
842,Maruti Suzuki Swift Select Variant,Maruti,2008,"1,75,000","58,000 kms",Diesel
843,Maruti Suzuki Alto 800 Lx,Maruti,2019,"4,00,000","1,500 kms",Petrol
844,Toyota Innova 2.5 Z Diesel 7 Seater,Toyota,2011,"7,50,000","75,000 kms",Diesel
845,Any type car avaiabel hare...comercica,Any,r...,"1,70,000",NaN,NaN
846,Maruti Suzuki Alto 800,Maruti,2016,"2,50,000","2,450 kms",Petrol
847,Maruti Suzuki Alto AX,Maruti,2019,"4,25,000","1,625 kms",Petrol
848,Maruti Suzuki Alto 800 Lx,Maruti,2019,Ask For Price,"1,500 kms",Petrol

In [63]:
print("Original rows:", len(df))

print(
    "Suspicious manufacturers:",
    df["company"]
    .astype("string")
    .str.strip()
    .str.lower()
    .isin(["any", "7", "9", "2012"])
    .sum()
)

Original rows: 892
Suspicious manufacturers: 4

In [64]:
import pandas as pd
from pathlib import Path

# Load the original dataset
PROJECT_ROOT = Path.cwd().parent
DATA_PATH = PROJECT_ROOT / "data" / "quikr_car.csv"

df = pd.read_csv(DATA_PATH)

# Clean manufacturer names
df["company"] = df["company"].astype("string").str.strip()

# Identify invalid manufacturers
invalid_values = {"any", "nan", "none", "null", "unknown"}

invalid_company = (
    df["company"].isna()
    | df["company"].str.lower().isin(invalid_values)
    | df["company"].str.fullmatch(r"\d+", na=False)
)

# Exclude generic advertisements
generic_ad = (
    df["name"]
    .astype("string")
    .str.strip()
    .str.lower()
    .str.startswith(("any type car", "7 seater", "9 seater"), na=False)
)

# Get valid manufacturer names
companies = sorted(
    df.loc[~invalid_company & ~generic_ad, "company"]
    .dropna()
    .unique()
    .tolist()
)

print(f"Total manufacturers: {len(companies)}")

Total manufacturers: 44

In [65]:
for i, manufacturer in enumerate(companies, start=1):
    print(f"{i}. {manufacturer}")

1. Audi
2. BMW
3. Chevrolet
4. Commercial
5. Datsun
6. Fiat
7. Force
8. Ford
9. Hindustan
10. Honda
11. Hyundai
12. I
13. Jaguar
14. Jeep
15. Land
16. MARUTI
17. Mahindra
18. Maruti
19. Mercedes
20. Mini
21. Mitsubishi
22. Nissan
23. Renault
24. Sale
25. Skoda
26. Swift
27. TATA
28. Tara
29. Tata
30. Toyota
31. URJENT
32. Used
33. Volkswagen
34. Volvo
35. Well
36. Yamaha
37. all
38. i
39. scratch
40. sell
41. selling
42. tata
43. urgent
44. very

In [66]:
import pandas as pd
from pathlib import Path

data_dir = Path("../data")

quikr = pd.read_csv(data_dir / "quikr_car.csv")
car_data = pd.read_csv(data_dir / "car_data.csv")

print("QUIKR DATASET")
print("Shape:", quikr.shape)
print("Columns:", quikr.columns.tolist())
display(quikr.head(3))

print("\nCAR DATASET")
print("Shape:", car_data.shape)
print("Columns:", car_data.columns.tolist())
display(car_data.head(3))

QUIKR DATASET
Shape: (892, 6)
Columns: ['name', 'company', 'year', 'Price', 'kms_driven', 'fuel_type']

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol

CAR DATASET
Shape: (301, 9)
Columns: ['Car_Name', 'Year', 'Selling_Price', 'Present_Price', 'Kms_Driven', 'Fuel_Type', 'Seller_Type', 'Transmission', 'Owner']

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0

In [67]:
for name, df in {
    "Quikr": quikr,
    "Car data": car_data,
}.items():
    print(f"\n--- {name} ---")
    print("Rows:", len(df))
    print("Missing values:")
    print(df.isna().sum())
    print("\nSample values:")
    for col in df.columns:
        print(f"{col}: {df[col].dropna().astype(str).unique()[:5].tolist()}")

--- Quikr ---
Rows: 892
Missing values:
name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

Sample values:
name: ['Hyundai Santro Xing XO eRLX Euro III', 'Mahindra Jeep CL550 MDI', 'Maruti Suzuki Alto 800 Vxi', 'Hyundai Grand i10 Magna 1.2 Kappa VTVT', 'Ford EcoSport Titanium 1.5L TDCi']
company: ['Hyundai', 'Mahindra', 'Maruti', 'Ford', 'Skoda']
year: ['2007', '2006', '2018', '2014', '2015']
Price: ['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000']
kms_driven: ['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms']
fuel_type: ['Petrol', 'Diesel', 'LPG']

--- Car data ---
Rows: 301
Missing values:
Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

Sample values:
Car_Name: ['ritz', 'sx4', 'ciaz', 'wagon r', 'swift']
Year: ['2014', '2013', '2017', '2011', '2018']
Selling_Price: ['3.35', '4.75', '7.25', '2.85', '4.6']
Present_Price: ['5.59', '9.54', '9.85', '4.15', '6.87']
Kms_Driven: ['27000', '43000', '6900', '5200', '42450']
Fuel_Type: ['Petrol', 'Diesel', 'CNG']
Seller_Type: ['Dealer', 'Individual']
Transmission: ['Manual', 'Automatic']
Owner: ['0', '1', '3']

In [68]:
import re
import pandas as pd

def normalize_name(value):
    value = str(value).lower()
    return re.sub(r"[^a-z0-9]", "", value)

# Standardize the manufacturer/model names for exploratory matching.
quikr["match_name"] = (
    quikr["company"].fillna("").astype(str)
    + " "
    + quikr["name"].fillna("").astype(str)
).map(normalize_name)

car_data["match_name"] = car_data["Car_Name"].map(normalize_name)

quikr["match_fuel"] = quikr["fuel_type"].fillna("").str.lower().str.strip()
car_data["match_fuel"] = car_data["Fuel_Type"].fillna("").str.lower().str.strip()

# Compare model names and fuel types without assuming the prices are equivalent.
quikr_names = set(quikr["match_name"])
car_names = set(car_data["match_name"])

print("Unique normalized Quikr names:", len(quikr_names))
print("Unique normalized Car data names:", len(car_names))
print("Exact name overlaps:", len(quikr_names & car_names))

print("\nCar data price ranges (in lakh, as represented in this dataset):")
print(car_data[["Selling_Price", "Present_Price"]].describe())

print("\nCar data manufacturing years:")
print(car_data["Year"].value_counts().sort_index())

Unique normalized Quikr names: 523
Unique normalized Car data names: 97
Exact name overlaps: 0

Car data price ranges (in lakh, as represented in this dataset):
       Selling_Price  Present_Price
count     301.000000     301.000000
mean        4.661296       7.628472
std         5.082812       8.644115
min         0.100000       0.320000
25%         0.900000       1.200000
50%         3.600000       6.400000
75%         6.000000       9.900000
max        35.000000      92.600000

Car data manufacturing years:
Year
2003     2
2004     1
2005     4
2006     4
2007     2
2008     7
2009     6
2010    15
2011    19
2012    23
2013    33
2014    38
2015    61
2016    50
2017    35
2018     1
Name: count, dtype: int64